version: '3'

services:
  mc-server:
    container_name: mc-server
    image: 'itzg/minecraft-server:java8-jdk'
    restart: always
    environment:
      EULA: "TRUE"
      VERSION: "1.15"
      TYPE: "SPIGOT"
      ENABLE_RCON: true
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
      - "25575:25575"
    volumes:
      - mc-server-data:/data

volumes:
  mc-server-data: {}