version: '3'

services:
  mc-server:
    image: 'itzg/minecraft-server:java8-jdk'
    restart: always
    environment:
      EULA: "TRUE"
      VERSION: "1.15"
      TYPE: "SPIGOT"
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
    volumes:
      - mc-server-data:/data

volumes:
  mc-server-data: {}