name: Build And Deploy
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Install SSH Pass
        run: sudo apt-get install -y sshpass
      - name: Build with Maven
        run: mvn package
      - name: List items
        run: cd target
      - name: Deploy to server
        run: ls
