name: Build and Publish Shadow JAR on Tag

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Build shaded jar
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '21'
          cache: 'gradle'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build
        run: ./gradlew --no-daemon clean build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: mchunt-shadow-jar
          path: build/libs/*.jar
          if-no-files-found: error
