name: Build and Publish Shadow JAR on Tag

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Build JAR for version ${{ github.ref_name }}
    runs-on: ubuntu-latest
    env:
      VERSION: ${{ github.ref_name }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '21'
          cache: 'gradle'

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: '8.9'

      - name: Build (propagate version)
        run: gradle --no-daemon clean build -PprojectVersion=${{ env.VERSION }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: mchunt-${{ env.VERSION }}
          path: build/libs/*.jar
          if-no-files-found: error

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: build/libs/*.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
