name: Build and Publish Shadow JAR on Tag

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Build shaded jar
    runs-on: ubuntu-latest
    env:
      VERSION: ${{ github.ref_name }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'gradle'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build (propagate version)
        run: ./gradlew --no-daemon clean build -PprojectVersion=${{ env.VERSION }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: mchunt-${{ env.VERSION }}
          path: build/libs/*.jar
          if-no-files-found: error
